version: "3.9"

volumes:
    postgres_database:
        external: true

services:
  webserver:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - "22:22"
      # - "9000:9000"
    links: 
      - postgres
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      # - ${WEBHOOK_SCRIPT_DIR-./webhook/scripts/redeploy.sh}:/var/scripts/redeploy.sh
      # - ${WEBHOOK_CONFIG_DIR-./webhook}:/var/webhook
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      PGSQL_ROOT_PASSWORD: ${PGSQL_PASSWORD}  
    networks: 
    - lapp-stack
    
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    image: postgres:${DBVERSION}
    restart: always
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    volumes:
       - postgres_database:${PGSQL_DATA_DIR}
    ports:
      - "${HOST_MACHINE_PGSQL_PORT}:5432"
    networks: 
      - lapp-stack
  adminer:
    image: adminer
    container_name: '${COMPOSE_PROJECT_NAME}-adminer'
    links:
      - postgres
    restart: always
    ports:
      - ${HOST_MACHINE_PMA_PORT}:8080
    networks: 
      - lapp-stack
networks: 
  lapp-stack:  